version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/zookeeper:3.5.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
networks:
  parrot:
    name: parrot_default
    driver: bridge