version: "3"
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/zookeeper:3.4.13
    ports:
      - 127.0.0.1:2181:2181
      - 127.0.0.1:2888:2888
      - 127.0.0.1:3888:3888
