version: "2"

services:

    zookeeper:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/zookeeper:latest
        networks:
            - hadoop
        volumes:
            - zookeeper_data:/zookeeper/data
            - zookeeper_logs:/zookeeper/logs
            - zookeeper_conf:/opt/zookeeper/conf

        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"

volumes:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    default:
        driver: bridge
