version: "2"

services:

    zookeeper:
        build:
            context: .
            dockerfile: Dockerfile
            args:
               httpProxyUrl: http://10.0.2.2:3128
               httpsProxyUrl: http://10.0.2.2:3128
               httpProxyHost: 10.0.2.2
               httpProxyPort: 3128
        image: mcapitanio/zookeeper:latest
        networks:
            - hadoop
        volumes:
            - zookeeper_data:/zookeeper/data
            - zookeeper_logs:/zookeeper/logs
            - zookeeper_conf:/opt/zookeeper/conf

        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
            - "8099:8099"

volumes:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    hadoop:
        driver: bridge
