version: "3"
services:
  zookeeper:
    container_name: zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/zookeeper:3.5.13
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888