version: '3'
services:
  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/zookeeper:latest
    networks:
    - hadoop
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    - 4200:4200
    environment:
      SERVER_HTTP_PORT: 9000
      API_HOST: localhost
      API_PORT: 9000
networks:
  default:
    external:
      name: hadoop
  hadoop:
    driver: bridge
