version: "2"

services:

    zookeeper:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/zookeeper:3.5.3
        networks:
            - hadoop
        volumes:
            - zookeeper_data:/tmp/zookeeper
            - zookeeper_logs:/opt/zookeeper/logs
            - zookeeper_conf:/opt/zookeeper/conf

        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
            - "8080:8080"

volumes:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    hadoop:
        driver: bridge
