version: "3"

services:

    zookeeper:
        build:
            context: .
            dockerfile: Dockerfile
        image: parrotstream/zookeeper:3.5.3
        networks:
            - parrot
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
            - "8080:8080"

networks:
    parrot:
        driver: bridge
